import { LEVELS, levelFromId, rebuildCounters } from './requirements.js';


// ── BUILD ──
export function buildMarkdown(project, reqs, categories) {
    const now = new Date();
    const dateStr = now.toISOString().split("T")[0];
    const timeStr = now.toTimeString().slice(0,8); 

    let md = `# Requirements — ${project.name}\n\n`;
    md += `> Generated by [ReqStack](https://github.com/davidMadueke/ReqStack) on ${dateStr} at ${timeStr}\n\n`;
    md += `---\n\n` ;

    // The summary table
    const counts = {sys: 0 , sub: 0, der: 0};
    reqs.forEach(r => counts[r.level]++);

    md += `## Summary\n\n`;
    md += `| Level | Count |\n|---|---|\n`;
    md += `| System | ${counts.sys} |\n`;
    md += `| Subsystem | ${counts.sub} |\n`;
    md += `| Derived | ${counts.der} |\n`;
    md += `| **Total** | **${reqs.length}** |\n\n`;
    md += `---\n\n`;


    function writeCategory(catId, allCategories, depth){
        const cat = allCategories.find(c => c.id === catId);
        const heading = "#".repeat(Math.min(depth+2, 6)); // lowest depth is a Heading 3 markdown header
        const catName  = cat ? cat.name : 'Uncategorised';

        md += `${heading} ${catName}\n`;
        md += `<!-- reqstack:category id="${catId}" -->\n\n`;

        //requirements in current category
        const catReqs = reqs.filter(r => r.categoryId === catId);
        catReqs.forEach(r => writeReqs(r));

        // perform recursion to get the children
        const children = allCategories.filter(c => c.parentCategoryId === catId);
        children.forEach(c => writeCategory(c.id, allCategories, depth+1));
    }

    function writeReqs(r) {
    md += `### \`${r.id}\`\n\n`;
    if (r.parent)     md += `*Parent: \`${r.parent}\`*\n\n`;
    if (r.categoryId) md += `<!-- reqstack:categoryId="${r.categoryId}" -->\n\n`;
    md += `${r.text}\n\n`;
    
  }

  // Root categories (no parent)
  const rootCats = categories.filter(c => c.parentCategoryId === null);

  if (rootCats.length > 0) {
    md += `## Requirements\n\n`;
    rootCats.forEach(c => writeCategory(c.id, categories, 1));
  }

  // Uncategorised requirements
  const uncategorised = reqs.filter(r => !r.categoryId);
  if (uncategorised.length > 0) {
    md += `## Uncategorised\n\n`;
    uncategorised.forEach(r => writeReqs(r));
  }

  return md;

}